<?php
return array(
"Afeganistao",
"Africa do Sul",
"Albania",
"Algeria",
"Alemanha",
"Angola",
"Anguila",
"Antarctica",
"Antigua e Barbuda",
"Antilhas Neerlandesas",
"Arabia Saudita",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijao",
"Bahamas",
"Bangladesh",
"Barbados",
"Barem",
"Belgica",
"Belize",
"Benin",
"Bermudas",
"Bielorrussia",
"Bolivia",
"Bosnia e Herzegovina",
"Botswana",
"Brasil",
"Brunei",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Butao",
"Camboja",
"Camaroes",
"Canada",
"Cabo Verde",
"Catar",
"Cazaquistao",
"Chade",
"Chile",
"China",
"Chipre",
"Colombia",
"Comoros",
"Coreia do Norte",
"Coreia do Sul",
"Costa do Marfim",
"Costa Rica",
"Croacia",
"Cuba",
"Dinamarca",
"Dominica",
"Equador",
"Egipto",
"El Salvador",
"Espanha",
"Emirados Arabes Unidos",
"Eritrea",
"Eslovaquia",
"Eslovenia", 
"Estados Federados da Micronesia",
"Estados Unidos da America",
"Estonia",
"Etiopia",
"Fiji",
"Filandia",
"Filipinas",
"Franca",
"Gabao",
"Gambia",
"Gana",
"Georgia",
"Gibraltar",
"Granada",
"Grecia",
"Gronelandia",
"Guadalupe",
"Guam",
"Guatemala",
"Guiana Francesa",
"Guiana",
"Guine Equatorial",
"Guine",
"Guine-Bissau",
"Haiti",
"Honduras",
"Hong Kong",
"Hungria",
"Iemen",
"Ilha Bouvet",
"Ilha Norfolk",
"Ilha do Natal",
"Ilha Pitcairn",
"Ilha da Reuniao",
"Ilhas Cayman",
"Ilhas Cocos (Keeling)",
"Ilhas Cook",
"Ilhas de Heard e McDonald",
"Ilhas Falkland (Ilhas Malvinas)",
"Ilhas Faroe",
"Ilhas Georgia do Sul e Sandwich do Sul",
"Ilhas Marshall",
"Ilhas Menores Afastadas dos Estados Unidos",
"Ilhas Salomao",
"Ilhas Virgens Americanas",
"Ilhas Virgens Britanicas",
"India",
"Indonesia",
"Irao",
"Iraque",
"Irlanda",
"Islandia",
"Israel",
"Italia",
"Jamaica",
"Japao",
"Jibuti",
"Jordania",
"Koweit",
"Laos",
"Lesoto",
"Letonia",
"Libano",
"Liberia",
"Libia",
"Lituania",
"Luxemburgo",
"Macao",
"Macedonia do Norte",
"Madagascar",
"Maiote",
"Malasia",
"Malawi",
"Maldivas",
"Mali",
"Malta",
"Marianas Setentrionais",
"Marrocos",
"Martinica",
"Mauritania",
"Mauricia",
"Mexico",
"Mocambique",
"Moldavia",
"Mongolia",
"Monserrate",
"Myanmar (Birmania)",
"Namibia",
"Nauru",
"Nepal",
"Nicaragua",
"Niger",
"Nigeria",
"Niue",
"Noruega",
"Nova Zelandia",
"Novo Caledonia",
"Oma",
"Paises Baixos",
"Palau",
"Panama",
"Papua-Nova Guine",
"Paquistao",
"Paraguai",
"Peru",
"Polinesia Francesa",
"Polonio",
"Porto Rico",
"Portugal",
"Quenia",
"Quirguistao",
"Quiribati",
"Reino Unido",
"Republica Centro-Africana",
"Republica Checa",
"Republica Democratica do Congo",
"Republica Dominicana",
"Romenia",
"Ruanda",
"Russia",
"Samoa",
"Samoa Americana",
"Santa Helena",
"Santa Lucia",
"Sara Ocidental",
"Sao Cristovao e Neves",
"Sao Pedro e Miquelao",
"Sao Tome e Principe",
"Sao Vicente e Granadinas",
"Seicheles",
"Senegal",
"Serra Leoa",
"Servia e Montenegro",
"Singapura",
"Siria",
"Somalia",
"Sri Lanka",
"Suazilandia",
"Sudao",
"Suecia",
"Suica",
"Suriname",
"Svalbard e Jan Mayen",
"Tailandia",
"Taiwan",
"Tajiquistao",
"Tanzania",
"Terras Austrais e Antarticas Francesas",
"Territorio do Oceano Indico Britanico",
"Territorios Palestinianos",
"Timor-Leste",
"Togo",
"Tonga",
"Toquelau",
"Trinidad e Tobago",
"Tunisia",
"Turcas e Caicos",
"Turquemenistao",
"Turquia",
"Tuvalu",
"Ucrania",
"Uganda",
"Uruguai",
"Uzbequistao",
"Vanuatu",
"Venezuela",
"Vietname",
"Wallis e Futuna",
"Zambia",
"Zimbabue"
);
?>