<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('adminheader');
?>

<div class="container">
    <div class="row">
        <form action="<?=URL::toRoute('user/store') ?>" method="post">        
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="primeironome" class="form-label">Primeiro Nome</label>
                <input type="text" class="form-control" id="primeironome" name="primeironome">   
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="apelido" class="form-label">Apelido</label>
                <input type="text" class="form-control" id="apelido" name="apelido">   
            </div> 
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="telemovel" class="form-label">Telemovel</label>
                <input type="number" class="form-control" id="telemovel" name="telemovel">   
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="email" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email">   
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="morada" class="form-label">Morada</label>
                <input type="text" class="form-control" id="morada" name="morada">  
            </div>          
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="username" class="form-label">Username</label>
                <input type="text" class="form-control" id="username" name="username"> 
            </div>   
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="password" class="form-label">Password</label>
                <input type="password" class="form-control" id="password" name="password">   
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="role" class="form-label">role</label>
                <select name="role" id="role" required>
                    <option disabled selected value> -- select an option -- </option>                    
                        <option value="operador">Operador de Checkin</option>
                        <option value="gestor">Gestor de Voo</option>
                        <option value="administrador">administrador</option>
                </select> 
            </div>
            <div class="text-right">             
                <button class="btn btn-action" type="submit">Criar</button>
            </div>
        </form>
    </div>
</div>