<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('gestorvooheader');

//obtem os dados de todos os aeroportos
$aeroportos = Data::get('aeroportos');

?>

<div class="container">
    <div class="row">
    <form action="<?=URL::toRoute('voo/store') ?>" method="post">
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="origem" class="form-label" style="color:black;">Insira o aeroporto de origem</label></h1>
            <select name="idAeroportoOrigem" required style="font-size:22px;">
                <option disabled selected value> -- select an option -- </option>
                <?php foreach($aeroportos as $aeroporto){?>
                        <option value="<?=$aeroporto->id?>"><?=$aeroporto->nome?></option>
                    <?php }?>
            </select>

        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="origem" class="form-label" style="color:black;">Insira o aeroporto de destino</label></h1>
            <select name="idAeroportoDestino" required style="font-size:22px;">
                <option disabled selected value> -- select an option -- </option>
                <?php foreach($aeroportos as $aeroporto){?>
                        <option value="<?=$aeroporto->id?>"><?=$aeroporto->nome?></option>
                    <?php }?>
            </select>

        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="preco" class="form-label" style="color:black;">Insira o preco</label></h1>
            <input type = "text" class="form-cotrol" name="preco">
        </div>

        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="duracao" class="form-label" style="color:black;">Insira a duracao</label></h1>
            <input type = "text" class="form-cotrol" name="duracao">
        </div>

        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
            <h1><label for="distancia" class="form-label" style="color:black;">Insira a distancia</label></h1>
            <input type = "text" class="form-cotrol" name="distancia">
        </div>

        <div class="col-12 text-right">
        <br><br>
			<button class="btn btn-action" type="submit">Criar</button>
		</div>
    </form>
    </div>

</div>
