<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('gestorvooheader');

$voos = Data::get('voos');
$aeroportos = Data::get('aeroportos');
?>

<style>

    table {
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
</style>



<div class="container">
    <table>
        <tr>
            <th>Origem</th>
            <th>Destino</th>
        </tr>   
        <?php foreach($voos as $voo){?>
        <tr>
            <td>
                
                <?php                                                              
                    $aeroportoOrigem = Aeroporto::find_by_idAeroporto($voo->idaeroportoorigem);
                    echo $aeroportoOrigem->nome; ?>
            </td>
            <td>
                <?php
                    $aeroportoDestino = Aeroporto::find_by_idAeroporto($voo->idaeroportodestino);
                    echo $aeroportoDestino->nome;
                ?>
            </td>
            <td>
                <a href="<?=URL::toRoute('voo/edit', $voo->id) ?>" class="btn btn-warning" role="button">Editar</a>
                <a href="<?=URL::toRoute('voo/destroy', $voo->id) ?>" class="btn btn-danger" role="button">Apagar</a>
                <a href="<?=URL::toRoute('escala/create', $voo->id) ?>" class="btn btn-primary" role="button">Escalas</a>
            </td>
        </tr>
        <?php } ?>     
    </table>
    <br>   
    <a href="<?= URL::toRoute('voo/create') ?>" class="btn btn-primary">Criar Voo</a> 
</div> 

