<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

use function Composer\Autoload\includeFile;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('gestorvooheader');

$plane = Data::get('plane');
Debug::barDump($plane);


?>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

<script>
    //obtem o valor da dropdown
    $(document).ready(function() {
        $("select.marca").change(function() {
            var marca = $(this).children("option:selected").val();
        });
    });
</script>
<div class="container">
    <div class="row">
        <form action="<?= URL::toRoute('plane/update', $plane->id) ?>" method="post">
            <!--************************************************** AVIOES ****************************************************************************************-->
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="marca" class="form-label">Marca</label>
                <input type="text" class="form-control" id="marca" name="marca" value="<?php echo $plane->marca ?>">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="modelo" class="form-label">Modelo</label>
                <input type="text" class="form-control" id="modelo" name="modelo" value="<?php echo $plane->modelo ?>">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="npassageiros" class="form-label">Nr Passageiros</label>
                <input type="text" class="form-control" id="npassageiros" name="npassageiros" value="<?php echo $plane->npassageiros ?>">
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="referencia" class="form-label">Referencia</label>
                <input type="text" class="form-control" id="referencia" name="referencia" disabled value="<?php echo $plane->referencia ?>">
                <br>
            </div>
            <div class="text-right">
                <button class="btn btn-action" type="submit">Editar</button>
            </div>
        </form>
    </div>
</div>