<?php

use ArmoredCore\Controllers\BaseController;
use ArmoredCore\Interfaces\ResourceControllerInterface;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Post;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\View;

/**
 * CRUD Resource Controller for ActiveRecord Model Aeroporto
 *
 * Code generated by WebLogicMVC Code Builder
 *
 * Date: 2021-05-26
 *
 * WL Code Builder developed by Sílvio Priem Mendes
 * *
 */
class AeroportoController extends BaseController implements ResourceControllerInterface
{
    /**
     * Returns index view with all records
     */
    public function index()
    {
        //$this->authFilterRole('administrador');
        $aeroportos = Aeroporto::all();
        return View::make('aeroporto.index', ['aeroportos' => $aeroportos]);
    }


    /**
     * Returns a view with a form to create a new record
     */
    public function create()
    {
        return View::make('aeroporto.create');
    }


    /**
     * Receives new record data through POST method and stores it in the DB table
     */
    public function store()
    {
        //create new resource (activerecord/model) instance with data from POST
        //your form name fields must match the ones of the table fields
        $aeroporto = new Aeroporto(Post::getAll());

        if($aeroporto->is_valid()){
            $aeroporto->save();
            Redirect::toRoute('aeroporto/index');
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('aeroporto/create', ['aeroporto' => $aeroporto]);
        }
    }


    /**
     * return a detailed view with record where PK = $id
     */
    public function show($id)
    {
        $aeroporto = Aeroporto::find([$id]);

        if (is_null($aeroporto)) {
            //TODO redirect to standard error page
        } else {
            return View::make('aeroporto.show', ['aeroporto' => $aeroporto]);
        }
    }


    /**
     * return a editable form view with record where PK = $id
     */
    public function edit($id)
    {
        $aeroporto = Aeroporto::find([$id]);   

        if (is_null($aeroporto)) {
            //TODO redirect to standard error page
        } else {
            return View::make('aeroporto.edit', ['aeroporto' => $aeroporto]);
        }
    }


    /**
     * Receives record data through POST method and updates it in the DB table
     */
    public function update($id)
    {
        //find resource (activerecord/model) instance where PK = $id
        //your form name fields must match the ones of the table fields
        $aeroporto = Aeroporto::find([$id]);
        $aeroporto->update_attributes(Post::getAll());

        if($aeroporto->is_valid()){
            $aeroporto->save();
            Redirect::toRoute('aeroporto/index');
        } else {
            //redirect to form with data and errors
            Redirect::flashToRoute('aeroporto/edit', ['aeroporto' => $aeroporto]);
        }
    }


    /**
     * deletes the record where PK = $id
     */
    public function destroy($id)
    {
        $aeroporto = aeroporto::find([$id]);
        $aeroporto->delete();
        Redirect::toRoute('aeroporto/index');
    }
}
?>