<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('gestorvooheader');
$aeroportos = Data::get('aeroportos');
?>

<div class="container">
    <div class="row">
        <form action="<?=URL::toRoute('escala/store') ?>" method="post">
        <br>
            <!--************************************************** AEROPORTO DE ORIGEM ****************************************************************************************-->
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="origem" class="form-label">Aeroporto de origem</label>
                <select name="idaeroportoorigem" id="idaeroportoorigem" required>
                    <option disabled selected value> -- select an option -- </option>
                    <?php foreach($aeroportos as $aeroporto){?>
                        <option value="<?=$aeroporto->id?>"><?=$aeroporto->nome?></option>
                    <?php }?>
                </select>                               
            </div>
            <!--************************************************** AEROPORTO DE DESTINO ****************************************************************************************-->
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="destino" class="form-label">Aeroporto de destino</label>
                <select name="idaeroportodestino" id="idaeroportodestino" required>
                    <option disabled selected value> -- select an option -- </option>
                    <?php foreach($aeroportos as $aeroporto){?>
                        <option value="<?=$aeroporto->id?>"><?=$aeroporto->nome?></option>
                    <?php }?>
                </select>
            </div>       
            <!--************************************************** DISTANCIA ****************************************************************************************-->             
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
                    <label for="distancia" class="form-label text-align:center;">Distância</label>
                    <input type="text" class="form-control text-align:center;" id="distancia" name="distancia" required> 
                </div>
                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4"></div>
            </div>
            <!--************************************************** DIA DE PARTIDA ****************************************************************************************-->
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="origem" class="form-label">Dia de partida</label>
                <input type="date" class="form-control" id="origem" name="data_hora_origem" value="<?php echo date('Y-m-d') ?>" min="<?php echo date('Y-m-d') ?>">
            </div>
            <!--************************************************** DIA DE REGRESSO ****************************************************************************************-->
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="destino" class="form-label">Dia de regresso</label>
                <input type="date" class="form-control" id="destino" name="data_hora_destino" min="<?php echo date('Y-m-d') ?>" required>
            </div>
            <div class="text-right">
            <br><br>
                <button class="btn btn-action" type="submit">Criar</button>
            </div>
        </form>
    </div>
</div>
