<?php

use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('operadorheader');

$passagens = Data::get('passagens');

$idUser = authManager::getLoggedID();
$user = User::find([$idUser]);

?>

<style>
    table {
        border-collapse: collapse;
        width: 100%;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
</style>

<div class="container">
    <table>
        <tr>
            <br>
            <th>Origem</th>
            <th>Destino</th>
            <th>Preço</th>
            <th>Passageiro</th>
            <th>Checkin</th>
        </tr>
        <?php foreach ($passagens as $passagem) { ?>
            <tr>
                <td>
                    <?php
                        $voo = Voo::find_by_idVoo($passagem->idvooida);
                        $aeroportoOrigem = Aeroporto::find_by_idAeroporto($voo->idaeroportoorigem);
                        echo $aeroportoOrigem->nome;                        
                    ?>
                </td>
                <td>
                    <?php
                        $aeroportoDestino = Aeroporto::find_by_idAeroporto($voo->idaeroportodestino);
                        echo $aeroportoDestino->nome;
                    ?>
                </td>
                <td>
                    <?php
                        echo $passagem->preco . '€';
                    ?>
                </td>
                <td>
                    <?php 
                        echo $user->primeironome . " " . $user->apelido; 
                    ?>
                </td>
                <td>
                    <?php 
                        echo $passagem->checkin;
                    ?>
                </td>
                <td>                
                    <a href="<?=URL::toRoute('passagemvendas/update', $passagem->id) ?>" class="btn btn-primary" role="button">Checkin</a>
                    <a href="<?=URL::toRoute('passagemvendas/show', $voo->id) ?>" class="btn btn-success" role="button">Ver</a>                   
                </td>
            </tr>
        <?php } ?>
    </table>
</div>