<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

use function Composer\Autoload\includeFile;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('adminheader');

?>

<div class="container">
    <div class="row">
        <form action="<?=URL::toRoute('aeroporto/store') ?>" method="post">        
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="destino" class="form-label">Cidade</label>
                <input type="text" class="form-control" id="cidade" name="cidade">   
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="destino" class="form-label">Morada</label>
                <input type="text" class="form-control" id="morada" name="morada">   
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <label for="destino" class="form-label">Nome</label>
                <input type="text" class="form-control" id="nome" name="nome"> 
                <br>  
            </div>            
            <div class="text-right">             
                <button class="btn btn-action" type="submit">Criar</button>
            </div>
        </form>
    </div>
</div>