<?php
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Debug;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

//***************INCLUIR O LAYOUT*****
Layout::includeLayout('adminheader');

$aeroporto = Data::get('aeroporto');


?>

<!--fazer o resto da pag e usar foreach para obter os dados dos aeroportos-->

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Nome: <?php echo $aeroporto->nome ?></h1>
        </div>
        <div class="col-12">
            <h1>Cidade: <?php echo $aeroporto->cidade ?></h1>
        </div>
        <div class="col-12">
            <h1>Pais: <?php echo $aeroporto->pais ?></h1>
        </div>
        <div class="col-12">
            <h1>Morada: <?php echo $aeroporto->morada ?></h1>            
        </div>     
        <br>   
        <a href="<?= URL::toRoute('aeroporto/edit', $aeroporto->id) ?>" class="btn btn-primary">Editar</a>   
        <a href="<?= URL::toRoute('aeroporto/destroy', $aeroporto->id) ?>" class="btn btn-danger">Apagar</a>               
    </div>
</div>