<?php
use ArmoredCore\WebObjects\URL;
?>
<!doctype html>
<html lang="pt-pt">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Registo Formulário</title>
</head>
<body>
    <div class="container">
        <form action="<?=URL::toRoute('login/doregistration') ?>" method="POST">
            <div class="mb-3">
                <label for="primeiroNome" class="form-label">Insira o seu nome</label>
                <input type="text" class="form-control" id="nome" name="primeiroNome">
            </div>
            <div class="mb-3">
                <label for="apelido" class="form-label">Insira o seu apelido</label>
                <input type="text" class="form-control" id="apelido" name="apelido">
            </div>
            <div class="mb-3">
                <label for="email" class="form-label">Insira o seu email</label>
                <input type="email" class="form-control" id="email" aria-describedby="emailHelp" name="email">
            </div>            
            <div class="mb-3">
                <label for="morada" class="form-label">Insira a sua morada</label>
                <input type="text" name="morada" id="morada" class="form-control">
            </div>
            <div class="mb-3">
                <label for="telemovel" class="form-label">Insira o seu telefone</label>
                <input type="number" class="form-control" id="telefone" name="telemovel">
            </div>
            <div class="mb-3">
                <label for="username" class="form-label">Insira o seu username</label>
                <input type="text" class="form-control" id="username" name="username">
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">Insira a sua password</label>
                <input type="password" class="form-control" id="password" name="password">
            </div>
            <button type="submit" class="btn btn-primary">Submeter</button>
        </form>
    </div>


<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>

